# Generated by Django 5.1.1 on 2024-10-29 01:58

import data.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earring',
            fields=[
                ('id', models.CharField(default='E-', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('total_weight', models.TextField()),
                ('gold_net_weight', models.TextField()),
                ('gems_1', models.TextField()),
                ('gems_2', models.TextField()),
                ('gems_3', models.TextField()),
                ('a_ywrt', models.TextField()),
                ('latkha', models.TextField()),
                ('price', models.BigIntegerField()),
                ('purchased', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EPRSet',
            fields=[
                ('id', models.CharField(default='ERP-', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('total_weight', models.TextField()),
                ('gold_net_weight', models.TextField()),
                ('gems_1', models.TextField()),
                ('gems_2', models.TextField()),
                ('gems_3', models.TextField()),
                ('a_ywrt', models.TextField()),
                ('latkha', models.TextField()),
                ('price', models.BigIntegerField()),
                ('purchased', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Handchain',
            fields=[
                ('id', models.CharField(default='H-', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('total_weight', models.TextField()),
                ('gold_net_weight', models.TextField()),
                ('gems_1', models.TextField()),
                ('gems_2', models.TextField()),
                ('gems_3', models.TextField()),
                ('a_ywrt', models.TextField()),
                ('latkha', models.TextField()),
                ('price', models.BigIntegerField()),
                ('purchased', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, storage=data.storage.ClassSpecificStorage(location='images/'), upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Necklace',
            fields=[
                ('id', models.CharField(default='N-', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('total_weight', models.TextField()),
                ('gold_net_weight', models.TextField()),
                ('gems_1', models.TextField()),
                ('gems_2', models.TextField()),
                ('gems_3', models.TextField()),
                ('a_ywrt', models.TextField()),
                ('latkha', models.TextField()),
                ('price', models.BigIntegerField()),
                ('purchased', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pendant',
            fields=[
                ('id', models.CharField(default='P-', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('total_weight', models.TextField()),
                ('gold_net_weight', models.TextField()),
                ('gems_1', models.TextField()),
                ('gems_2', models.TextField()),
                ('gems_3', models.TextField()),
                ('a_ywrt', models.TextField()),
                ('latkha', models.TextField()),
                ('price', models.BigIntegerField()),
                ('purchased', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.CharField(default='R-', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('total_weight', models.TextField()),
                ('gold_net_weight', models.TextField()),
                ('gems_1', models.TextField()),
                ('gems_2', models.TextField()),
                ('gems_3', models.TextField()),
                ('a_ywrt', models.TextField()),
                ('latkha', models.TextField()),
                ('price', models.BigIntegerField()),
                ('purchased', models.BooleanField()),
            ],
        ),
    ]
