# Generated by Django 5.1.1 on 2024-10-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendant',
            name='a_ywrt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendant',
            name='gems_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendant',
            name='gems_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendant',
            name='gems_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendant',
            name='latkha',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendant',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
