# Generated by Django 5.1.2 on 2024-10-30 06:44

import data.models
import data.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content_type',
            field=models.ForeignKey(default=data.models.get_default_necklace_content_type_id, limit_choices_to={'model__in': ['necklace', 'eprset', 'earring', 'ring', 'handchain', 'pendant']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, storage=data.storage.ClassSpecificStorage(location='images/'), upload_to=data.models.get_upload_path),
        ),
    ]
