# Generated by Django 5.1.1 on 2024-10-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_pendant_a_ywrt_alter_pendant_gems_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earring',
            name='a_ywrt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earring',
            name='gems_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earring',
            name='gems_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earring',
            name='gems_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earring',
            name='latkha',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earring',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eprset',
            name='a_ywrt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eprset',
            name='gems_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eprset',
            name='gems_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eprset',
            name='gems_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eprset',
            name='latkha',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eprset',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handchain',
            name='a_ywrt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handchain',
            name='gems_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handchain',
            name='gems_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handchain',
            name='gems_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handchain',
            name='latkha',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handchain',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='a_ywrt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='gems_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='gems_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='gems_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='latkha',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ring',
            name='a_ywrt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ring',
            name='gems_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ring',
            name='gems_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ring',
            name='gems_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ring',
            name='latkha',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ring',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
