# Generated by Django 5.1.1 on 2024-11-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eprset',
            name='id',
            field=models.CharField(default='EPR-', max_length=255, primary_key=True, serialize=False),
        ),
    ]
