# Generated by Django 5.1.1 on 2024-10-29 02:26

import data.models
import data.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data', '0004_rename_product_id_image_object_id_image_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content_type',
            field=models.ForeignKey(default=data.models.get_default_necklace_content_type, limit_choices_to={'model__in': ['necklace', 'eprset', 'earring', 'ring', 'handchain', 'pendant']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, storage=data.storage.ClassSpecificStorage(location='images/'), upload_to='get_upload_path'),
        ),
    ]
