# Generated by Django 5.1.2 on 2024-11-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_earring_date_created_eprset_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earring',
            name='purchased_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eprset',
            name='purchased_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handchain',
            name='purchased_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='necklace',
            name='purchased_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendant',
            name='purchased_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ring',
            name='purchased_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earring',
            name='purchased',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eprset',
            name='purchased',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handchain',
            name='purchased',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='necklace',
            name='purchased',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pendant',
            name='purchased',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ring',
            name='purchased',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
